### ISSUE TITLE
"Keep all squares open" not working on Firefox Dev.

### ISSUE THREAD

**Issue by Luisoncm** [etacarinaea/startpage#12]
Hi there,

The option "Keep all squares open" is not wotrking on Firefox Developer 73.0b12 (64-bit), Windows 10. I marked the option an all the boxes stayed closed. They didn't open even on mouse hover, so I had to remove the extension and star over again. 

I love the design and the simplicity.  ;)

**Comment by etacarinaea** [comment]
Thanks for reporting the bug! It's fixed now

> They didn't open even on mouse hover, so I had to remove the extension and star over again.

Sorry you had to start all over again. They still opened when using the keyboard for me, but that's probably not a very intuitive solution if the squares aren't opening at all on mouse hover. I should probably add a little gear icon or something like that somewhere to open the config menu.
