### ISSUE TITLE
Config pop up menu

### ISSUE THREAD

**Issue by OskarWoeltje** [etacarinaea/startpage#13]
Hey, absolutely love this project to clean up my startpage and make my chrome workflow more enjoyable, my only problem is, I don't know how to code, been experimenting a little on the side to get an overview, and I can't for the live of me figure out how to collapse that super annoying pop up menu that tells you the -config -help commands. I would be super grateful if you could help me solve this problem.
Thanks!

**Comment by etacarinaea** [comment]
Thanks for the feedback, I'm glad you like it! I was able to reproduce the issue and fixed it yesterday. The new version was just approved on the chrome web store today so you should be able to update the extension now. As far as I can tell it's fixed now but let me know if you run into any problems
